# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d71402a84a570f1596a7d6e62c031e574e32c80e3a1c7ef52251c62ee274c09cdb966e3731d9fc8f9d86d3f95d8540142e4db02c68108ba3ea5b4c24ffd2cca

test:
  secret_key_base: a02cd0b7c0852f4eb37f73a68f0a073abf4741c6b800f463201a13ed7cff43241eb5fc1fedc1afb3cf704b58230e5d97eb57d59b02b7d524b83a8a247f1175cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
